version: '3.8'

services:
  app:
    build: .
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - bot_network


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge